# Generated by Django 3.2.12 on 2024-04-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldiagno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referdata',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_pregnancies', models.IntegerField()),
                ('glucose_level', models.FloatField()),
                ('insulin_level', models.FloatField()),
                ('bmi', models.FloatField()),
                ('age', models.IntegerField()),
                ('blood_pressure', models.FloatField()),
                ('skin_thickness', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
