# Generated by Django 3.2.12 on 2024-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldiagno', '0002_auto_20240415_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='referdata',
            name='dp_function',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referdata',
            name='outcome',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
