# Generated by Django 3.2.12 on 2024-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldiagno', '0003_auto_20240415_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_patient',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_pregnancies', models.IntegerField()),
                ('glucose_level', models.FloatField()),
                ('insulin_level', models.FloatField()),
                ('bmi', models.FloatField()),
                ('dp_function', models.FloatField()),
                ('age', models.IntegerField()),
                ('blood_pressure', models.FloatField()),
                ('skin_thickness', models.FloatField()),
                ('outcome', models.IntegerField()),
            ],
        ),
    ]
