# Generated by Django 3.2.12 on 2024-04-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mldiagno', '0004_new_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_patient',
            name='outcome',
        ),
    ]
